Algoritmo "Trabalhando com tipos"

Var
palavra, palavraA, palavraB: caractere
numero, numeroA, numeroB: inteiro

Inicio

Escreval ("Informe a primeira palavra")
leia (palavra)
Escreval ("Informe a segunda palavra")
leia (palavraA)
Escreval ("Informe o primeiro numero")
leia (numero)
Escreval ("Informe o segundo numero")
leia (numeroA)
palavraB <- palavra + " " + palavraA
numeroB <- numero + numeroB
Escreval(palavraB, numeroB)


Fimalgoritmo