Algoritmo "debug"

Var
x, y, z: inteiro

Inicio

//nessa aula o professor explicou como usar a funçao debug no visualg para
//executar o codigo passo a passo e resolver erros no estilo "dividir para conquistar"
//isso é feito por meio do f2, que faz uma marcaçao e o programa funciona até ela
//depois disso precisa ser feita uma autorização manual para que o resto do codigo rode
leia (x)
leia (y)
z <- x + y
escreval (z)

Fimalgoritmo