Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 6/5/2025
tipo
cadastroCliente = registro
nome: caracter
rg: caracter
idade: inteiro
fimregistro
Var
// Seção de Declarações das variáveis 
cliente1: cadastroCliente

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite seu nome:")
leia (cliente1.nome)
Escreval ("Digite seu rg:")
leia (cliente1.rg)
Escreval ("Digite sua idade:")
leia (cliente1.idade)

escreval(cliente1.nome, cliente1.rg, cliente1.idade)

Fimalgoritmo