/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {
    
        System.out.println("Ola mundo");
        System.out.println("Meu segundo comando de saida");
    }
}
