/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {

        int codigoProduto = 2;

        switch(codigoProduto){
        case 1:
            break;

        case 2:
            break;
        //break serve para que cada case seja execultado uma unica vez

        default:
            break;
        /*default serve para que todos os casos que nao estao sendo tratados
         em cases sejam executados pela config predefinida*/
        }
        
    }
}
