/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {


        /*
        > maior
        >= maior ou igual
        < menor
        <= menor igual
        == igual
        != diferente
        */
        int media = 7;
        if (media >= 7) {
            if (media == 10){
                System.out.println("Parabéns, você passou com nota máxima");
            }
            System.out.println("Parabéns, você foi aprovado!");
        }
        else{
            System.out.println("Você foi reprovado!");
        }
        
    }
}
