/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {
//Estudo das variaveis e suas aplicações
        //toda variavel deve começar com letra minuscula
        int idade;
        //o tipo vem antes da nomenclatura da variavel
        //essa é a criaçao de uma variavel com um valor definido
        int idade2 = 0;
        //variaveis podem ser criadas em todo o campo de void main(campo)
        
        /*int, float, double, char, byte e boolean sao todos os tipos de variaveis que existem 
        ao nosso dispor na linguagem java, isso excluindo os tipos primitivos
        int é uma variavel de tipo inteiro
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        float é uma var de tipo flutuante
        */
        float cotacaoDolar = 5.0f;
        /*
        double é usada para armazenar números de ponto flutuante com dupla precisão (ou seja, números decimais 
        com maior precisão que o tipo float).
        */
        double cotacaoEuro = 6.0d;
        /*
        char é uma variavel que armazena um unico caracter (comumente usada para designio de generos e etc)
        */
        char genero = 'M';
        /*
        byte é usado para armazenar números inteiros pequenos. Ele é especialmente útil quando você quer economizar memória em situações como arrays grandes 
        ou manipulação de dados binários (como arquivos ou transmissões de rede).
        Este vai de -128 a 127 em inteiros
        */
        byte pontos = 0;
        /*
        boolean é um tipo primitivo usado para representar valores lógicos: true (verdadeiro) ou false (falso).
        */
        boolean estadoCadastro = false;
        /*
        o tipo string armazena um conjunto de caracteres, ao contrario do tipo char
        */
        String nome = "Matheus Jesus de Oliveira";


    }
}
