/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {
        //como o java não possui um leitor de dados, temos que importa-lo
        import java.util.Scanner;
        //criando o scanner
        Scanner leitor = new Scanner(System.in);    
        //lendo um valor inteiro
        int idade = leitor.nextInt();
        //lendo um valor flutuante
        float cotDollar = leitor.nextFloat();
        //
        double cotEuro = leitor.nextDouble();
        //lendo texto (frases)
        string nome = leitor.nextLine();
        //lendo texto (apenas uma palavra)
        string nome1 = leitor.next();

        //saída de dados
        //println pula linha ao contrario de print
        System.out.println("texto que será exibido no console")
        System.out.print("texto que tambem será exibido, dessa vez sem pular linha")

    }
}
