/*
 * This source file was generated by the Gradle 'init' task
 */
package LPA3_START_1CAPGEMNI;

public class Aula4C {
    
    public static void main(String[] args) {
    
        System.out.println("Ola mundo");
        System.out.println("Meu segundo comando de saida");
    }
}
