/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.gradleproject1;

public class App {
    
    public static void main(String[] args) {
    
        System.out.println("Ola mundo");
        System.out.println("Meu segundo comando de saida");
        //AULA 4D - COMENTARIOS
        //COMENTARIOS DE LINHA
        /*COMENTARIOS MAIS EXTENSOS
        PARA DETALHES MAIS ABRANGENTES
        */
        
        /**ESSE COMENTARIO É ESPECIAL, ELE É UM COMENTARIO DE DOCUMENTAÇÃO, COMO UMA DOCSTRING E PODE SER UTILIZADO NOVAMENTE SE 
         * QUISERMOS RETORNA-LO, POR EXEMPLO, POR .TXT ETC */
    
    }
}
